eshopper/cart1/routes.py
from flask import  render_template, request, session, redirect, url_for,flash,Blueprint
from eshopper.products.modules import product
from eshopper.cart1.modules import Cart
from eshopper import app, db, bcrypt,params
from eshopper import home
cart = Blueprint('cart', __name__)


# for individual item
@cart.route("/cart1")
def view_cart():
    if ('user' in session):
        cart1 = Cart.query.filter_by(user=session['user']).all()
        cart2 = Cart.query.filter_by(user=session['user']).all()
        total1=0
        for cart2 in cart2:
            int(cart2.total)
            total1=total1+cart2.total


        return render_template('cart1.html', cart1=cart1,total1=total1)
    else:
        flash('User is not logged in, Please login before adding items to wishlist', 'danger')
        return redirect(url_for("user.login"))


@cart.route("/cart/<int:product11>")
def add_to_cart(product11):
    if ('user' in session):

        cart_data = product.query.filter_by(productid=product11).first()
        cart1 = Cart(productid=cart_data.productid, user=session['user'], productname=cart_data.productname, productprice=cart_data.productprice, categoryname=cart_data.categoryname, image=cart_data.image, brand=cart_data.brand, stock=cart_data.stock, discount=cart_data.discount, status=cart_data.status, totaltax=cart_data.costaftertax, total=cart_data.total)
        db.session.add(cart1)
        db.session.commit()
    else:
        flash('User is not logged in, Please login before adding items to wishlist', 'danger')
        redirect(url_for("user.login"))
    return redirect(url_for("home.home1"))


@cart.route("/delete/<int:sno>")
def delete_cart_item(sno):
    if ('user' in session):
        delete = Cart.query.filter_by(user=session['user'],sno=sno).first()
        db.session.delete(delete)
        db.session.commit()
    return redirect('/cart1')

eshopper/chatbot/routes.py
from flask import Flask, render_template, request, session, redirect, url_for,flash,Blueprint
from eshopper import app, db, bcrypt,mail,params
from eshopper.chatbot import chatbot

chatbot = Blueprint('chatbot', __name__)

@chatbot.route("/chatbot")
def hom():
    return render_template("chatbot.html")

@chatbot.route("/get")
def get_bot_response():
    userText = request.args.get('msg')
    return str(chatbot.get_response(userText))

eshopper/products/routes.py
from flask import  render_template, request, session, redirect, url_for,flash,Blueprint
from eshopper import app, db, bcrypt,params
from eshopper.products.modules import product
from eshopper.user.modules import user_login
from eshopper.home.routes import searchbar
import math
from eshopper.wishlist.modules import Wishlist
products = Blueprint('products', __name__)


# for individual item
@products.route("/productname/<string:product11>", methods=['GET'])
def post_route(product11):
    int (product11)
    product1 = product.query.filter_by(productid=product11).first()
    return render_template('product-details.html', product1=product1)



# for sub brand item like samsung/mobilephones
@products.route("/productbrand/<string:brands>/<string:item>", methods=['GET'])
def post_route1(brands,item):
    page = request.args.get('page', 1, type=int)
    brandname = product.query.filter_by(brand=brands,categoryname=item).paginate(page=page, per_page=6)
    return render_template('productpage-probrand.html', brandname=brandname)


@products.route("/productbrand/<string:item>", methods=['GET'])
def post_route2(item):
    page = request.args.get('page', 1, type=int)
    brandname1 = product.query.filter_by(brand=item).paginate(page=page, per_page=6)
    return render_template('productpage-brand1.html', brandname1=brandname1,item=item)


@products.route("/page")
def page():
    products = product.query.filter_by().all()
    last = math.ceil(len(products) / int(params['no_of_posts']))
    # posts=posts()
    page = request.args.get('page')
    if (not str(page).isnumeric()):
        page = 1
        page = int(page)
    products = products[(page - 1) * int(params['no_of_posts']): (page - 1) * int(params['no_of_posts']) + int(params['no_of_posts'])]

    if page == 1:
        prev = "#"
        next = "/?page=" + str(page + 1)
    elif page == last:
        prev = "/?page=" + str(page - 1)
        next = "#"
    else:
        prev = "/?page=" + str(page - 1)
        next = "/?page=" + str(page + 1)
    return render_template('productpage.html', params=params, products=products, prev=prev, next=next)


@products.route("/searchbar", methods=['GET'])
def post_route4():
    search=searchbar.serach_string
    brandname2 = product.query.filter_by(brand=search).all()
    return render_template('productpage.html', brandname2=brandname2)


@products.route("/productcategory/<string:item>", methods=['GET'])
def post_route3(item):
    if request.method == 'GET':
        if request.form['submit_button'] == 'Do Something':
            pass  # do something
        elif request.form['submit_button'] == 'Do Something Else':
            pass  # do something else
        else:
            pass  # unknown
    page = request.args.get('page', 1, type=int)
    brandcategory = product.query.filter_by(categoryname=item).paginate(page=page, per_page=2)
    return render_template('productpage-category.html', brandcategory=brandcategory,item=item)


@products.route("/productpage")
def productpage():
    page = request.args.get('page', 1, type=int)
    product_pro = product.query.filter_by().paginate(page=page, per_page=5)
    try:
        loginn = user_login.query.filter_by(email=session['user']).first()
        if 'user' in session:
            name=loginn.firstname
    except:
        name=""
    return render_template('productpage.html', product=product_pro)


# for individual item
@products.route("/wishlist/<string:product11>", methods=['GET'])
def wishlist(product11):
    int (product11)
    page = request.args.get('page', 1, type=int)
    product1 = product.query.filter_by(productid=product11).first()
    return render_template('product-details.html', product1=product1)

eshopper/templates/contact.html
{% extends "layout.html" %}
{% block body %}
	 <div id="contact-page" class="container">
    	<div class="bg">
	    	<div class="row">    		
	    		<div class="col-sm-12">    			   			
					<h2 class="title text-center">Contact <strong>Us</strong></h2>    			    				    				
				 	
    		<div class="row">  	
	    		<div class="col-sm-8">
	    			<div class="contact-form">
	    				<h2 class="title text-center">Get In Touch</h2>
	    				<div class="status alert alert-success" style="display: none"></div>
				    	<form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
				            <div class="form-group col-md-6">
				                <input type="text" name="username" id="username" class="form-control" required="required" placeholder="Name">
				            </div>
				            <div class="form-group col-md-6">
				                <input type="email" name="email" id="email" class="form-control" required="required" placeholder="Email">
				            </div>
				            <div class="form-group col-md-6">
				                <input type="phone" name="phone" id="phone" class="form-control" required="required" placeholder="Phone Number">
				            </div>
				            <div class="form-group col-md-12">
				                <input type="text" name="sub" id="sub" class="form-control" required="required" placeholder="Subject">
				            </div>
				            <div class="form-group col-md-12">
				                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your Message Here"></textarea>
				            </div>                        
				            <div class="form-group col-md-12">
				                <input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit">
				            </div>
				        </form>
	    			</div>
	    		</div>
	    		<div class="col-sm-4">
	    			<div class="contact-info">
	    				<h2 class="title text-center">Contact Info</h2>
	    				<address>
	    					<p>E-Shopper Inc.</p>
							<p>935 W. Webster Ave New Streets Chicago, IL 60614, NY</p>
							<p>Newyork USA</p>
							<p>Mobile: +2346 17 38 93</p>
							<p>Fax: 1-714-252-0026</p>
							<p>Email: info@e-shopper.com</p>
	    				</address>
	    				<div class="social-networks">
	    					<h2 class="title text-center">Social Networking</h2>
							<ul>
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-google-plus"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-youtube"></i></a>
								</li>
							</ul>
	    				</div>
	    			</div>
    			</div>    			
	    	</div>  
    	</div>	
    </div><!--/#contact-page-->
	
	 {% endblock %}

eshopper/templates/forgotpassword.html
{% extends "layout.html" %}
{% block body %}
<div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                 <center> {{ message }}</center>
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

        </div>
 <div class="wrapper">
      <div class="title">Login Form</div>
      <form method="post" action="">

        <div class="field">
          <input type="text" required name="name">
          <label>Email Address</label>
        </div>
        <div class="field">
          <input type="password" required name="OTP">
          <label>OTP</label>
        </div>

        <div class="field">
          <input type="submit" value="process">
        </div>

      </form>
    </div>

 {% endblock %}

eshopper/templates/login (1).html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Login Form | Eshopper</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static',filename='css1/style.css')}}">
  </head>
  <body>
    <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                 <center> {{ message }}</center>
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

        </div>
    <div class="wrapper">
      <div class="title">Login Form</div>
      <form method="post" action="">

        <div class="field">
          <input type="text" required name="name">
          <label>Email Address</label>
        </div>
        <div class="field">
          <input type="password" required name="password">
          <label>Password</label>
        </div>
        <div class="content">
          <div class="checkbox">
            <input type="checkbox" id="remember-me">
            <label for="remember-me">Remember me</label>
          </div>
          <div class="pass-link"><a href="{{ url_for('reset_request') }}">Forgot password?</a></div>
        </div>
        <div class="field">
          <input type="submit" value="Login">
        </div>
        <div class="signup-link">Not a member? <a href="/register">Signup now</a></div>
      </form>
    </div>

  </body>
</html>

eshopper/templates/productpage-probrand.html
{% extends "layout.html" %}
{% block body %}
<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											<a href="/productcategory/mobilephones">Mobile Phones</a>
										</a>
									</h4>
								</div>
								<div id="sportswear" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="/productbrand/samsung/mobilephones">Samsung </a></li>
											<li><a href="/productbrand/apple/mobilephones">Apple </a></li>
											<li><a href="/productbrand/oneplus/mobilephones">OnePlus </a></li>
											<li><a href="/productbrand/oppo/mobilephones">Oppo</a></li>
											<li><a href="/productbrand/redmi/mobilephones">Redmi </a></li>
											<li><a href="/productbrand/realme/mobilephones">Realme </a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#mens">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											<a href="/productcategory/washingmachine">Washing Machines</a>
										</a>
									</h4>
								</div>
								<div id="mens" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="/productbrand/samsung/washingmachine">samsung</a></li>
											<li><a href="/productbrand/lg/washingmachine">Lg</a></li>
											<li><a href="/productbrand/godrej/washingmachine">godrej</a></li>
											<li><a href="/productbrand/whirlpool/washingmachine">Whirlpool</a></li>
											<li><a href="/productbrand/onida/washingmachine">Onida</a></li>
											<li><a href="/productbrand/haier/washingmachine">Haier</a></li>
											<li><a href="/productbrand/panasonic/washingmachine">Panasonic</a></li>
										</ul>
									</div>
								</div>
							</div>


							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#womens">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											<a href="/productcategory/aircondition">Aircondition</a>
										</a>
									</h4>
								</div>
								<div id="womens" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="/productbrand/samsung/aircondition">Samsung</a></li>
											<li><a href="/productbrand/lg/aircondition">Lg</a></li>
											<li><a href="/productbrand/whirlpool/aircondition">whirpool</a></li>
											<li><a href="/productbrand/godrej/aircondition">godrej</a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/washingmachine">REFRIGERATORS</a></h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/tablates">Tablates</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/watches">Watches</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/wired_earphones">Earphones</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/laptops">Laptops</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/tv">T.v</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/fans">Fans</a></h4>
								</div>
							</div>

						</div><!--/category-products-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href="/productbrand/apple"> <span class="pull-right">(50)</span>Apple</a></li>
									<li><a href="/productbrand/samsung"> <span class="pull-right">(56)</span> Samsung</a></li>
									<li><a href="/productbrand/lg"> <span class="pull-right">(27)</span>Lg</a></li>
									<li><a href="/productbrand/xiomi"> <span class="pull-right">(32)</span>Xiomi</a></li>
									<li><a href="/productbrand/whirlpool"> <span class="pull-right">(5)</span>Whirpool</a></li>
									<li><a href="/productbrand/realme"> <span class="pull-right">(9)</span>Realme</a></li>
									<li><a href="/productbrand/oppo"> <span class="pull-right">(4)</span>Oppo</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->

						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->

						<div class="shipping text-center"><!--shipping-->
							<img src="{{ url_for('static',filename='images/home/shipping.jpg')}}" alt="" />
						</div><!--/shipping-->
						<div class="shipping text-center"><!--shipping-->
							<img src="{{ url_for('static',filename='images/home/shipping.jpg')}}" alt="" />
						</div><!--/shipping-->

					</div>
				</div>
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">All products</h2>
                    {% for brandname in brandname.items %}
                    {% set fname = 'images/product/' + brandname.image %}
                    <div class="col-sm-4">
                        <div class="product-image-wrapper">
                            <div class="single-products">
                                <div class="productinfo text-center">
                                    <a href="/productname/{{brandname.productid}}"><img
                                            src="{{ url_for('static',filename=fname)}}" height="250px;"/></a><br>
                                    <br>
                                    <p><a href="/productname/{{brandname.productid}}">{{brandname.productname}}</a></p>
                                    <h2>{{brandname.productprice}}</h2>
                                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Buy
                                        Now</a>
                                </div>
                                <div class="product-overlay">
                                    <div class="overlay-content">

                                    </div>
                                </div>
                            </div>
                            <div class="choose">
                                <ul class="nav nav-pills nav-justified">
                                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to Cart</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>


                    {% endfor %}
				</div>
<style>
	nextbtn {
    position: absolute;
    left: 0px;
    top: 52px
</style>
							<div class="nextbtn">
                    {% for page_num in brandname.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)
                    %}

               {% if page_num %}
                    {% if brandname.page == page_num %}
                    <a class="btn btn-info mb-4" href="{{ url_for('products.productpage', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                    <a class="btn btn-outline-info mb-4" href="{{ url_for('products.productpage', page=page_num) }}">{{
                        page_num }}</a>
                    {% endif %}
                    {% else %}
                    ...
                    {% endif %}
                    {% endfor %}


                </div>
			</div>
		</div>
	</section>
	
	 {% endblock %}

eshopper/templates/productpage.html
{% extends "layout.html" %}
{% block body %}

<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											<a href="/productcategory/mobilephones">Mobile Phones</a>
										</a>
									</h4>
								</div>
								<div id="sportswear" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="/productbrand/samsung/mobilephones">Samsung </a></li>
											<li><a href="/productbrand/apple/mobilephones">Apple </a></li>
											<li><a href="/productbrand/oneplus/mobilephones">OnePlus </a></li>
											<li><a href="/productbrand/oppo/mobilephones">Oppo</a></li>
											<li><a href="/productbrand/redmi/mobilephones">Redmi </a></li>
											<li><a href="/productbrand/realme/mobilephones">Realme </a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#mens">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											<a href="/productcategory/washingmachine">Washing Machines</a>
										</a>
									</h4>
								</div>
								<div id="mens" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="/productbrand/samsung/washingmachine">samsung</a></li>
											<li><a href="/productbrand/lg/washingmachine">Lg</a></li>
											<li><a href="/productbrand/godrej/washingmachine">godrej</a></li>
											<li><a href="/productbrand/whirlpool/washingmachine">Whirlpool</a></li>
											<li><a href="/productbrand/onida/washingmachine">Onida</a></li>
											<li><a href="/productbrand/haier/washingmachine">Haier</a></li>
											<li><a href="/productbrand/panasonic/washingmachine">Panasonic</a></li>
										</ul>
									</div>
								</div>
							</div>


							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#womens">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											<a href="/productcategory/aircondition">Aircondition</a>
										</a>
									</h4>
								</div>
								<div id="womens" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											<li><a href="/productbrand/samsung/aircondition">Samsung</a></li>
											<li><a href="/productbrand/lg/aircondition">Lg</a></li>
											<li><a href="/productbrand/whirlpool/aircondition">whirpool</a></li>
											<li><a href="/productbrand/godrej/aircondition">godrej</a></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/washingmachine">REFRIGERATORS</a></h4>
								</div>
							</div>

							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/tablates">Tablates</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/watches">Watches</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/wired_earphones">Earphones</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/laptops">Laptops</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/tv">T.v</a></h4>
								</div>
							</div>
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title"><a href="/productcategory/fans">Fans</a></h4>
								</div>
							</div>

						</div><!--/category-products-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								<ul class="nav nav-pills nav-stacked">
									<li><a href="/productbrand/apple"> <span class="pull-right">(50)</span>Apple</a></li>
									<li><a href="/productbrand/samsung"> <span class="pull-right">(56)</span> Samsung</a></li>
									<li><a href="/productbrand/lg"> <span class="pull-right">(27)</span>Lg</a></li>
									<li><a href="/productbrand/xiomi"> <span class="pull-right">(32)</span>Xiomi</a></li>
									<li><a href="/productbrand/whirlpool"> <span class="pull-right">(5)</span>Whirpool</a></li>
									<li><a href="/productbrand/realme"> <span class="pull-right">(9)</span>Realme</a></li>
									<li><a href="/productbrand/oppo"> <span class="pull-right">(4)</span>Oppo</a></li>
								</ul>
							</div>
						</div><!--/brands_products-->

						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->

						<div class="shipping text-center"><!--shipping-->
							<img src="{{ url_for('static',filename='images/home/shipping.jpg')}}" alt="" />
						</div><!--/shipping-->


					</div>
				</div>

						<div class="features_items"><!--features_items-->

						{% for product in product.items %}
						{% set fname = 'images/product/' + product.image %}
						 <div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<a href="/productname/{{product.productid}}"><img  src="{{ url_for('static',filename=fname)}}" height="250px;" /></a><br>
											<br><p><a href="/productname/{{product.productid}}">{{product.productname}}</a></p>
											<h2>{{product.productprice}}</h2>
											<a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Buy Now</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">

											</div>
										</div>
									</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to Cart</a></li>
									</ul>
								</div>
							</div>
						</div>

						{% endfor %}
</div>


<style>
	nextbtn {
    position: absolute;
    left: 0px;
    top: 52px
</style>
							<div class="nextbtn">
							{% for page_num in product.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if product.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('products.productpage', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('products.productpage', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}



					
				</div>
			</div>
		</div>
	</section>
	
	 {% endblock %}